title: Streamdata Gallery Accelerated Mobile Pages (AMP) URL
url: accelerated-mobile-pages-amp-url.streamdata.gallery
tag: Accelerated Mobile Pages (AMP) URL
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_user: streamdata-gallery
github_repo: accelerated-mobile-pages-amp-url
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
